apiVersion: v1
kind: Pod
metadata:
    name: multi
spec:
    volumes:
        - name: share-data
          emptyDir: {}
    containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: share-data
          mountPath: /usr/share/nginx/html
    - name: ftp-container
      image: fauria/vsftpd
      volumeMounts:
        - name: share-data
          mountPath: /pod-data
      env:
        - name: FTP_USER
          value: admin
        - name: FTP_PASS
          value: password